#!/bin/bash
#PBS -lwalltime=01:30:00
#PBS -lnodes=1:ppn=8
#PBS -W group_list=isis (ndssl?)
#PBS -q pecos_q@pecosq
#PBS -A pecos
#PBS -N FTLewis
#PBS -o /vbi/isis/isis_dtra/cell/3095/run/ef_3095.qlog
#PBS -j oe
NUM_PROCS=`/bin/cat $PBS_NODEFILE | /usr/bin/wc -l | /bin/sed "s/  //g"`
cd $PBS_O_WORKDIR
MPIRUN="mpiexec_mpt -n $NUM_PROCS"
$MPIRUN /vbi/projects/epifast/bin/EpiFast  /vbi/isis/isis_dtra/cell/3095/run/Configuration > /vbi/isis/isis_dtra/cell/3095/run/cout