###  Analysis of DTRA_AVstudy
###  Requires DetailStats.csv as generated by .... <fill in blanks here>


av = read.csv("DetailStats.csv")
summary(av)

pdf("Summary_Stats.pdf")

### Attack Rate
AR_hist = hist(av$attackRate)
barplot(AR_hist$counts,names.arg=AR_hist$breaks[1:23],xlab="Attack Rate",ylab="Frequency",main="")



require(rpart)
tt = rpart(av$attackRate~av$ve+av$vtd+av$other+av$cwtd+av$cwl)
plot(tt)
text(tt)


dev.off()
