#!/bin/bash
#PBS -lwalltime=01:30:00
#PBS -lnodes=1:ppn=8
#PBS -W group_list=isis (ndssl?)
#PBS -q pecos_q@pecosq
#PBS -A pecos
#PBS -N FTLewis-87
#PBS -o /Users/jamesschlitt/Desktop/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/ef_87.qlog
#PBS -j oe
NUM_PROCS=`/bin/cat $PBS_NODEFILE | /usr/bin/wc -l | /bin/sed "s/  //g"`
cd $PBS_O_WORKDIR
MPIRUN="mpiexec_mpt -n $NUM_PROCS"
$MPIRUN /vbi/projects/epifast/bin/EpiFast /Users/jamesschlitt/Desktop/Users/jamesschlitt/Desktop/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/config > /Users/jamesschlitt/Desktop/Users/jamesschlitt/Desktop/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/cout
