#!/bin/bash
#PBS -lwalltime=01:30:00
#PBS -lnodes=1:ppn=8
#PBS -W group_list=pecos
#PBS -q pecos_q@pecosq
#PBS -A pecos
#PBS -N FTLewis-95
#PBS -o /home/NDSSL/study/DTRA_AVstudy/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/ef_95.qlog
#PBS -j oe
NUM_PROCS=`/bin/cat $PBS_NODEFILE | /usr/bin/wc -l | /bin/sed "s/  //g"`
cd $PBS_O_WORKDIR
MPIRUN="mpiexec_mpt -n $NUM_PROCS"
$MPIRUN /vbi/projects/epifast/bin/EpiFast /home/NDSSL/study/DTRA_AVstudy/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/config > /home/NDSSL/study/DTRA_AVstudy/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/cout
