#!/bin/bash
#PBS -lwalltime=01:30:00
#PBS -lnodes=1:ppn=8
#PBS -W group_list=isis (ndssl?)
#PBS -q pecos_q@pecosq
#PBS -A pecos
#PBS -N FTLewis
#PBS -o users/thefolder/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/NoDiagAVExplicitFiles/ef_191.qlog
#PBS -j oe
NUM_PROCS=`/bin/cat $PBS_NODEFILE | /usr/bin/wc -l | /bin/sed "s/  //g"`
cd $PBS_O_WORKDIR
MPIRUN="mpiexec_mpt -n $NUM_PROCS"
$MPIRUN users/thefolder/epifast/bin/EpiFastusers/thefolder/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/NoDiagAVExplicitFiles/Configuration > users/thefolder/FtLewisStudy/vd28ve70active/avd10e87/wd10wl28wc25/NoDiagAVExplicitFiles/cout
